- name: Vars from local
  hosts: local
  connection: local
  vars_files:
  - Ansible_repo/varsfromfile.yaml
  tasks:
  - name: Vars from file
  ansible.builtin.debug:
    msg: "{{ COURSE }} is completed"